apiVersion: notification.toolkit.fluxcd.io/v1beta1
kind: Alert
metadata:
  name: team-on-call
  namespace: kus-spike
spec:
  providerRef:
    name: slack
  eventSeverity: info
  eventSources:
    - kind: GitRepository
      name: ruby-hello
    - kind: Kustomization
      name: ruby-hello
