apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: ruby-hello
  namespace: kus-spike
spec:
  interval: 5m
  path: "./deploy/manifests/"
  prune: true
  sourceRef:
    kind: GitRepository
    name: ruby-hello
  # validation: client
  timeout: 80s
